apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: radio-signals
resources:
  - 00-namespace.yaml
  - postgres-secret.yaml
  - postgres-config.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - ml-deployment.yaml
  - ml-service.yaml
  - backend-config.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
